name: run tests on pr

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Metadata
        id: docker-meta
        uses: docker/metadata-action@v5
        with:
          images: |
            docker.io/hronom/simple-rest-api
          tags: |
            type=raw,value=${{ github.run_number }}-tests-latest

      - name: Build container
        id: docker-build-push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}
          target: tests
          provenance: false
